project_id = "wtqloayzvoslgsgqjjin"

[functions.extract-article]
verify_jwt = false

[functions.generate-script]
verify_jwt = false

[functions.search-clips]
verify_jwt = false

[functions.generate-voice]
verify_jwt = false
